### ISSUE TITLE
Atoms, prefixed with dot don't work as macros parameters

### ISSUE THREAD

**Issue by svetlyak40wt** [mitranim/jisp#4]
I wanted to create a macros:

``` lisp
(mac http_call method url ...body
     `(do $http
         (,method ,url)                                                                                                                               (.success (fn data (do ,...body)))))
```

To be used like:

``` lisp
(http_call .get "/api/items/"
                      (= $scope.items data))
```

which should produce code like this:

``` lisp
(do $http
    (.get "/api/items/")
    (.success (fn data
                  (do (= $scope.items data)))))
```

But compiler says:

```
Error: unexpected .get in possible modes: emptyhash | hash | list | quote | unquote | spread | spread | atom

Tested against: (  :  )  (  isKey  :  (  `  ,  ...  …  isAtomString

Tokens: .get, "/api/permissions/", (, =, $scope.perms, data, ), ), (, http_get ...
    at Error (unknown source)
    at demand (/home/art/my-project/jisp/dev/jisp/lex.js:104:108)
    at lex (/home/art/my-project/jisp/dev/jisp/lex.js:170:22)
    at demand (/home/art/my-project/jisp/dev/jisp/lex.js:101:16)
    at lex (/home/art/my-project/jisp/dev/jisp/lex.js:170:22)
    at demand (/home/art/my-project/jisp/dev/jisp/lex.js:101:16)
    at lex (/home/art/my-project/jisp/dev/jisp/lex.js:161:21)
    at Object.compile (/home/art/my-project/jisp/dev/jisp/jisp.js:1571:20)
    at compileScript (/home/art/my-project/jisp/dev/jisp/command.js:170:25)
    at compilePath (/home/art/my-project/jisp/dev/jisp/command.js:127:15)
```

If i remove dot from `get`, then compilation succeed, but result is incorrect:

``` javascript
$http;
    ["/api/items/"]
      .success((function(data) {
        return ($scope.items = data);
      }));
```

**Comment by svetlyak40wt** [comment]
Think, nobody will work on this ever.

**Comment by mitranim** [comment]
At some point, I'd like to write a blog post _why_. My opinion of Lisps was already low and went lower after some professional experience with Clojure.

**Comment by svetlyak40wt** [comment]
It would be nice to read such post.
